import time
def book():
    print("This is the tutorial book!")
    time.sleep(3)
    while True:
        tutorial = input("What would you like to know about? (interact, examine, move, use, inventory, items, book generation, walls, Daniel Thrasher, leave): ")
        if tutorial == "interact":
            print("Interacting with an item either causes an item to be gained, or for something to occur or activate.")
            time.sleep(2)
            print("Sometimes this may be an ending, or a switch for another location.")
            time.sleep(2)
        elif tutorial == "examine":
            print("Examining an item reveals extra information about that item.")
            time.sleep(2)
            print("It may help you to solve a puzzle that you didn't know initially.")
            time.sleep(2)
        elif tutorial == "move":
            print("Moving means going to another location that is neither negative, nor restricted.")
            time.sleep(2)
            print("Often this will be revealed to you in location descriptions.")
            time.sleep(2)
            print("+x is for east, -x is for west, +y is for north, -y is for south.")
            time.sleep(2)
            print("Moving to an edge also allows you to access extra information in some locations.")
            time.sleep(2)
        elif tutorial == "use":
            print("When you get an item, often via interaction, it is put into your inventory and used.")
            time.sleep(2)
            print("Often there will be an indication to use an item.")
            time.sleep(2)
        elif tutorial == "inventory":
            print("Viewing your inventory lets you know what you have, should you forget.")
            time.sleep(2)
            print("Dropping an item means it goes out of your inventory, should you want to or not have enough space.")
            time.sleep(2)
        elif tutorial == "items":
            print("Items usually have specific functions to the storyline, or for easter eggs.")
            time.sleep(2)
            print("You get these items via interactions or random events.")
            time.sleep(2)
        elif tutorial == "book generation":
            print("There are three books in the game, and this is one of them.")
            time.sleep(2)
            print("You have a 1/10 chance to get another, and 1/50 chance to get another.")
            time.sleep(2)
            print("This chance is refreshed every time you launch the game.")
            time.sleep(2)
            print("Also, books and special delays do not change, regardless of what you entered at the start.")
            time.sleep(2)
        elif tutorial == "walls":
            print("Read the wall lore book for more information.")
            time.sleep(2)
        elif tutorial == "Daniel Thrasher":
            print("The greatest individual to ever live, Daniel Thrasher was declared missing in 2027.")
            time.sleep(2)
            print("He went inside of a dark castle-like place, and got lost.")
            time.sleep(2)
            print("He is presumed dead. Although...")
            time.sleep(2)
            print("Some think him still alive, a spirit, taking the form of any character he once presented as in his sketches.")
            time.sleep(2)
            print("All those who have claimed to see him have either died or escaped the castle walls.")
            time.sleep(2)
            print("Note down if you see him.")
            time.sleep(2)
            print("We need information on that. My idol won't have died for nothing.")
            time.sleep(2)
            print("At least I can watch his sketches forevermore...")
            time.sleep(2)
        elif tutorial == "leave":
            print("Book finished!")
            time.sleep(2)
            break
        
def fish_book():
    print("Fish do not fly.")
    time.sleep(2)
    print("'Truest information I've ever heard.' you think to yourself.")
    time.sleep(2)
    print("Book finished!")
    time.sleep(2)

def wall_lore_book():
    print("The book opens with a ferocity and mystery that you haven't seen before.")
    time.sleep(4)
    print("Legend has it, there is an omnipresent god locked in this castle.")
    time.sleep(2)
    print("They are linked to the walls of this place.")
    time.sleep(2)
    print("That's why the walls are so impenetrable.")
    time.sleep(2)
    print("There is an unending amount of energy inside these walls.")
    time.sleep(2)
    print("If you touch every one of these walls...")
    time.sleep(2)
    print("...something will happen.")
    time.sleep(2)
    print("No one knows what yet.")
    time.sleep(2)
    print("Well done if you found this book.")
    time.sleep(2)
    print("Will you be the one to activate the infinite energy stored within this place?")
    time.sleep(2)
    print("Oh yes, something else.")
    time.sleep(2)
    print("Legend says you must touch all of these walls in one go. Commitment issues or something, I guess.")
    time.sleep(2)
    print("No loading your saves, whatever that means.")
    time.sleep(2)
    print("Book finished!")
    time.sleep(2)
